model_name: transfuser
use_synthetic_sensors: False
use_real_sensors: True
max_num_agents: 64
trajectory_sample_interval: 5
used_cameras: ['cam_f0','cam_r0','cam_l0']
only_train_on_ego: True # only train on AV
metric_monitor: 'val/loss' # metric to monitor for early stopping



train_batch_size: 1
eval_batch_size: 1
max_epochs: 100
learning_rate: 1e-4 # 0.00075 # 1e-3 for lanegcn
learning_rate_sched: [ 10, 20, 30, 40, 50 ]
optimizer: Adam #According to PyTorch naming
scheduler: multistep # plateau, multistep
ewc_lambda: 2000

grad_clip_norm: 5





_target_: unitraj.models.transfuser.transfuser_agent.TransfuserAgent
_convert_: 'all'

config:
  _target_: unitraj.models.transfuser.transfuser_config.TransfuserConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False

checkpoint_path: null
